### ISSUE TITLE
unable to pull llama 3.1 on 0.09

### ISSUE THREAD

**Issue by wesowx** [pooyahrtn/RunpodOllama#12]
I've updated my container image to latest version 0.09 but when i try to use llama3.1 

**Runpod serverless**
Container image: pooyaharatian/runpod-ollama:0.0.9
Container start command: llama3.1:8b

I get an error
- The model you are attempting to pull requires a newer version of Ollama.

Any way to get around this?

**Comment by TimPietruskyRunPod** [comment]
@pooyahrtn I guess this requires an update of ollama right?

**Comment by wesowx** [comment]
> @pooyahrtn I guess this requires an update of ollama right?

Yes, i updated version to 0.3.4 in my fork and it works

**Comment by pooyahrtn** [comment]
@wesowx thanks!
