### ISSUE TITLE
(Error)  Command not found: run_proxy  

### ISSUE THREAD

**Issue by ZoccoCss** [pooyahrtn/RunpodOllama#2]
I've set up the Runpod endpoint and it's working properly with  `runpod_serverless_llm.py`. However when I run the `start-proxy.sh` I get a `Command not found: run_proxy` error. 

In the shell script there's a line with `poetry run run_proxy` that calls a file that doesn't exist in the repository.  I think you are referring to `ollama_runpod_proxy.py` but when I make the necessary changes to point to that file, I still get some errors (Now anOpenAIException). 

Should I continue to consider  `ollama_runpod_proxy.py` as the missing `run_proxy` file?

**Comment by pooyahrtn** [comment]
@ZoccoCss Thanks for sharing. Indeed `ollama_runpod_proxy.py` is the intended file.

**Comment by ZoccoCss** [comment]
Thank you @pooyahrtn for your quick response. I'm going to close this issue now. 

I'm still getting an anOpenAIException error. Probably I have an issue with the  config.yml. If I can't make it work I'll open a new issue.

**Comment by pooyahrtn** [comment]
@ZoccoCss I just fixed the script and added an example. Please let me know if it fixed the issue.
