### ISSUE TITLE
Unauthorized in the Cli

### ISSUE THREAD

**Issue by ZoccoCss** [pooyahrtn/RunpodOllama#3]
I'm testing the Cli using the following command. 

```
poetry run runpod-ollama  create-endpoint test  ollama_serverless_mistral
```

and I'm getting the following response.

```
Failed to create endpoint.
Unauthorized
```

I think that the issue comes from not pointing to my pod_id but I haven't been able to figure out where should I insert it.

**Comment by pooyahrtn** [comment]
@ZoccoCss I guess it should be related to the runpod's API token. Can you check your `.env` file and make sure the `RUNPOD_API_TOKEN` is defined there?

**Comment by ZoccoCss** [comment]
I created the ,env file as suggested in the Readme but I still get an error. 

![Screenshot_20240130_154434](https://github.com/pooyahrtn/RunpodOllama/assets/47893772/b43e14f0-a477-455f-afa0-34a4ea6a2d68)

I also tried exporting the token and got the same result.

**Comment by pooyahrtn** [comment]
@ZoccoCss could it be that your API key doesn’t have the write access?
![IMG_5943](https://github.com/pooyahrtn/RunpodOllama/assets/17365155/1f706ac9-0d0d-4f81-9840-976dfac126da)

**Comment by ZoccoCss** [comment]
Yes, that was the problem.  I'll be closing this issue.
