### ISSUE TITLE
Misc. Errors

### ISSUE THREAD

**Issue by ZoccoCss** [pooyahrtn/RunpodOllama#4]
I was able to use `runpod-ollama create-model phi 10` to create a new endpoint with a new template.  I selected a GPU in Runpod. However, I'm getting the following messages. 

![Screenshot_20240131_081606](https://github.com/pooyahrtn/RunpodOllama/assets/47893772/6bc5b6fa-2323-483a-b050-b2d0ed16dd01)

I ended the service running on the port and the error occurs on a different port.

**Comment by pooyahrtn** [comment]
@ZoccoCss thanks again. I just pushed a change. Can you check again?

**Comment by ZoccoCss** [comment]
Yes. Thank you @pooyahrtn. The port allocation is fixed and the example code runs.
