### ISSUE TITLE
Implement the same "Running ChooseYourOwnOpenAICompatibleProxy with Runpod Serverless" using other alternative LLM proxies 

### ISSUE THREAD

**Issue by distributev** [pooyahrtn/RunpodOllama#6]
In the Dockerfile we could do for instance 

1. FROM BerriAI/litellm (instead of FROM ollama/ollama:latest)
2. and then in start.sh replace the commands which starts ollama with the commands to start litellm
3. and then in runpod_wrapper.py call litellm api instead of ollama

would that work to achieve "Running LiteLLM with Runpod Serverless"?

Similarly the same can be done with 

# Other OpenAI compatible proxies which could also be potentially deployed in runpod serverless

https://github.com/mudler/LocalAI
https://github.com/ModelTC/lightllm

**Comment by TimPietrusky** [comment]
@distributev this sounds like a nice idea, as having an OpenAI-compatible API is super helpful to reuse already exisiting frameworks. What do you think @pooyahrtn?

**Comment by pooyahrtn** [comment]
That's a good point. However, Ollama started supporting OpenAI-compatible API [doc](https://ollama.com/blog/openai-compatibility). I think it'd be better to not add dependency to more external packages, and keep this package as lean as possible.
We still need to change this package by:
1. The `local_proxy` needs to accept any arbitrary `endpoint`.
2. The `runpod_wrapper` on the server should forward any arbitrary endpoints.

**Comment by pooyahrtn** [comment]
@distributev @TimPietrusky I created [this](https://github.com/pooyahrtn/RunpodOllama/pull/10) PR to support OpenAI's api. Let me know if you have any comments.

**Comment by TimPietrusky** [comment]
@pooyahrtn thank you very much. I'm just wondering if this is actually working like this when it is deployed on RunPod, have you tested it? Would be super nice if this is working. I was looking into this when I was using the [vllm-worker](https://github.com/runpod-workers/worker-vllm), but I didn't dig deep enough to find out how that worker actually exposes the OpenAI-compatible API.

**Comment by pooyahrtn** [comment]
@TimPietrusky 
> I'm just wondering if this is actually working like this when it is deployed on RunPod, have you tested it?

It actually works (thanks to the upgrade you made). I tested it on RunPod.

**Comment by pooyahrtn** [comment]
Closed in favour of [this commit](https://github.com/pooyahrtn/RunpodOllama/commit/6999032f4eb2c7e8f8ac9479a6a9ec49374c5ef1).
