### ISSUE TITLE
License and further development

### ISSUE THREAD

**Issue by TimPietrusky** [pooyahrtn/RunpodOllama#7]
I was wondering if you can provide a license for this repo, so that others can continue working on it. Because right now, this is impossible and I'm considering creating my own serverless-worker for RunPod, so that we can use ollama there. But I would rather help out here or fork it instead of starting from scratch. 

What are your thoughts @pooyahrtn?

**Comment by pooyahrtn** [comment]
Hey @TimPietrusky!
Great idea, thanks. I added an MIT license [0bba88d](https://github.com/pooyahrtn/RunpodOllama/commit/0bba88d8a56d2badc56dca0d5917f7aadea95a62).

I'd definitely appreciate any contribution.

**Comment by TimPietrusky** [comment]
@pooyahrtn thank you very much! Then let's get this going.
